{
  pkgs,
  username,
  ...
}: let
  terminal = "kitty";

  # Noctalia is now installed by Home Manager.
  # This points niri to the Home Manager/user-profile binary directly.
  noctaliaBin = "/home/${username}/.nix-profile/bin/noctalia-shell";

  layoutModule = import ./layout.nix {};

  keybindsModule = import ./keybinds.nix {
    inherit terminal noctaliaBin;
  };

  windowrulesModule = import ./windowrules.nix {};

  startupModule = import ./startup.nix {
    inherit noctaliaBin;
  };
in {
  programs = {
    niri = {
      enable = true;
    };
  };

  environment = {
    systemPackages = [
      pkgs.xwayland-satellite
    ];

    etc."niri/config.kdl".text = ''
      // Niri config
      // Generated by NixOS system config.

      ${layoutModule}

      ${keybindsModule}

      ${windowrulesModule}

      ${startupModule}

      environment {
          XDG_CURRENT_DESKTOP "niri"
          GTK_USE_PORTAL "1"
          MOZ_ENABLE_WAYLAND "1"
          QT_QPA_PLATFORM "wayland"
          ELECTRON_OZONE_PLATFORM_HINT "wayland"
          GDK_BACKEND "wayland,x11"
          GTK_THEME "catppuccin-mocha-mauve-standard:dark"
          TERMINAL "${terminal}"
      }

      hotkey-overlay {
          skip-at-startup
          hide-not-bound
      }

      prefer-no-csd

      screenshot-path "~/Pictures/Screenshots/Screenshot from %Y-%m-%d %H-%M-%S.png"
    '';
  };
}
