{
  imports = [
    ../features/terminal/omp
    ./nh.nix
    ./git.nix
    ./gtk.nix
    ../features/terminal/bat.nix
    ../features/terminal/eza.nix
    ./mpv.nix
    ./htop.nix
    ../features/terminal/fish.nix
    ../features/terminal/tmux.nix
    ../features/noctalia
    ../features/terminal/kitty.nix
    ./fastfetch
    ./utils.nix
    ./unfree.nix
    ./devkit.nix
    ./direnv.nix
    ./nixvim.nix
    ./lazygit.nix
  ];
}
