{
  imports = [
    ../features/terminal/omp
    ../features/terminal/nh.nix
    ../features/dev/git.nix
    ./gtk.nix
    ../features/terminal/bat.nix
    ../features/terminal/eza.nix
    ./mpv.nix
    ./htop.nix
    ../features/terminal/fish.nix
    ../features/terminal/tmux.nix
    ../features/noctalia
    ../features/terminal/kitty.nix
    ../features/shell/fastfetch
    ./utils.nix
    ./unfree.nix
    ../features/dev/devkit.nix
    ../features/terminal/direnv.nix
    ../features/editor/nixvim.nix
    ../features/dev/lazygit.nix
  ];
}
