{
  inputs,
  pkgs,
  ...
}: let
  terminal = "alacritty";
  browser = "zen-browser";

  system = pkgs.stdenv.hostPlatform.system;
  noctaliaPkg = inputs.noctalia.packages.${system}.default;
  noctaliaBin = "${noctaliaPkg}/bin/noctalia-shell";

  layoutModule = import ./layout.nix {};

  keybindsModule = import ./keybinds.nix {
    inherit terminal browser noctaliaBin;
  };

  windowrulesModule = import ./windowrules.nix {};

  startupModule = import ./startup.nix {
    inherit noctaliaBin;
  };
in {
  programs = {
    niri = {
      enable = true;
    };
  };

  environment = {
    systemPackages = [
      noctaliaPkg
    ];

    etc."xdg/niri/config.kdl".text = ''
      // Niri config
      // Generated by NixOS system config.

      ${layoutModule}

      ${keybindsModule}

      ${windowrulesModule}

      ${startupModule}

      environment {
          XDG_CURRENT_DESKTOP "niri"
          GTK_USE_PORTAL "1"
          MOZ_ENABLE_WAYLAND "1"
          QT_QPA_PLATFORM "wayland"
          ELECTRON_OZONE_PLATFORM_HINT "wayland"
          TERMINAL "${terminal}"
      }

      hotkey-overlay {
          skip-at-startup
      }

      prefer-no-csd

      screenshot-path "~/Pictures/Screenshots/Screenshot from %Y-%m-%d %H-%M-%S.png"
    '';
  };
}
